name: 'Snyk Monitor'
run-name: 'Update Snyk with latest vulnerability report'
on:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  snyk-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run Snyk to monitor for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
